/* Generated by the NeXT Project Builder 
   NOTE: Do NOT change this file -- Project Builder maintains it.
*/
extern "C"{
#import <appkit/appkit.h>
}

int main(int argc, char *argv[]) {

    [Application new];
    if ([NXApp loadNibSection:"CheckRIB.nib" owner:NXApp withNames:NO])
        [NXApp run];
        
    [NXApp free];
    exit(0);
    return(0);
}
