/******************************************************************************
FILE:               encmacos.c
LANGUAGE:           ANSI-C
SYSTEM:             ANSI
USER-INTERFACE:     ANSI
DESCRIPTION
    This file define the Macintosh encoding array.
AUTHORS
    <PJB> Pascal J. Bourguignon
MODIFICATIONS
    $Id: encmacos.c,v 1.1 2003/12/04 03:36:53 pjbpjb Exp $
    $Log: encmacos.c,v $
    Revision 1.1  2003/12/04 03:36:53  pjbpjb
    Cleaned-up.
    Moved bc*.[hc] in bclib.
    Fix.

    Revision 1.1  2002/08/11 02:36:41  pascal
    Fist check-in.
    
LEGAL
    Copyright Pascal J. Bourguignon 1991 - 1994
    All Rights Reserved.
    This program may not be included in any commercial product without the 
    author written permission. It may be used freely for any non-commercial 
    purpose, provided that this header is always included.
******************************************************************************/
#include <encmacos.h>

    BenEncodingTableT   MacintoshEncoding={
            "asciinul",
            "asciisoh",
            "asciistx",
            "asciietx",
            "asciieot",
            "asciienq",
            "asciiack",
            "asciibel",
            "asciibs",
            "asciiht",
            "asciilf",
            "asciivt",
            "asciiff",
            "asciicr",
            "asciiso",
            "asciisi",
            "asciidle",
            "asciidc1",
            "asciidc2",
            "asciidc3",
            "asciidc4",
            "asciinak",
            "asciisyn",
            "asciietb",
            "asciican",
            "asciiem",
            "asciisub",
            "asciiesc",
            "asciifs",
            "asciigs",
            "asciirs",
            "asciius",
            "space",
            "exclam",
            "quotedbl",
            "numbersign",
            "dollar",
            "percent",
            "ampersand",
            "quoteright",
            "parenleft",
            "parenright",
            "asterisk",
            "plus",
            "comma",
            "hyphen",
            "period",
            "slash",
            "zero",
            "one",
            "two",
            "three",
            "four",
            "five",
            "six",
            "seven",
            "eight",
            "nine",
            "colon",
            "semicolon",
            "less",
            "equal",
            "greater",
            "question",
            "at",
            "A",
            "B",
            "C",
            "D",
            "E",
            "F",
            "G",
            "H",
            "I",
            "J",
            "K",
            "L",
            "M",
            "N",
            "O",
            "P",
            "Q",
            "R",
            "S",
            "T",
            "U",
            "V",
            "W",
            "X",
            "Y",
            "Z",
            "bracketleft",
            "backslash",
            "bracketright",
            "asciicircum",
            "underscore",
            "quoteleft",
            "a",
            "b",
            "c",
            "d",
            "e",
            "f",
            "g",
            "h",
            "i",
            "j",
            "k",
            "l",
            "m",
            "n",
            "o",
            "p",
            "q",
            "r",
            "s",
            "t",
            "u",
            "v",
            "w",
            "x",
            "y",
            "z",
            "braceleft",
            "bar",
            "braceright",
            "asciitilde",
            "asciidel",
    /* "Ö","Ü","á","â","ë","ñ","ö","÷","’","◊","Ÿ","ÿ","⁄","€","›","‹", */
            "Adieresis",
            "Aring",
            "Ccedilla",
            "Eacute",
            "Ntilde",
            "Odieresis",
            "Udieresis",
            "aacute",
            "agrave",
            "acircumflex",
            "adieresis",
            "atilde",
            "aring",
            "ccedilla",
            "eacute",
            "egrave",
    /* "ﬁ","ﬂ","‚","‡","‰","Â","Á","Ì","Ï","Ó","","Ô","Û","Ú","Ù","ˆ", */
            "ecircumflex",
            "edieresis",
            "iacute",
            "igrave",
            "icircumflex",
            "idieresis",
            "ntilde",
            "oacute",
            "ograve",
            "ocircumflex",
            "odieresis",
            "otilde",
            "uacute",
            "ugrave",
            "ucircumflex",
            "udieresis",
    /* "≤"," ","¢","£","ß","∑","∂","˚","∞","†",nil,"¬","»",nil,"·","È", */
            "dagger",
            "degree",   /***/
            "cent",
            "sterling",
            "section",
            "bullet",
            "paragraph",
            "germandbls",
            "registered",
            "copyright",
            "trademarksans",
            "acute",
            "dieresis",
            "notequal",
            "AE",
            "Oslash",
    /* nil,"—",nil,nil,"•","ù","Ê",nil,nil,nil,nil,"„","Î",nil,"Ò","˘", */
            "infinity",
            "plusminus",
            "lessequal",
            "greaterequal",
            "yen",
            "mu",
            "partialdiff",
            "summation",
            "product",
            "pi",
            "integral",
            "ordfeminine",
            "ordmasculine",
            "Omega",
            "ae",
            "oslash",
    /* "ø","°","æ",nil,"¶",nil,nil,"´","ª","º","Ä","Å","Ñ","ï","Í","˙", */
            "questiondown",
            "exclamdown",
            "logicalnot",
            "radical",
            "florin",
            "approxequal",
            "Delta",
            "guillemotleft",
            "guillemotright",
            "ellipsis",
            "digitspace",       /*** unbreakable space = digitspace? ***/
            "Agrave",
            "Atilde",
            "Otilde",
            "OE",
            "oe",
    /* "±","–","™","∫","`","'","ü",Benil,"˝",Benil,"§","®","¨","≠","Æ","Ø", */
            "endash",
            "emdash",
            "quotedblleft",
            "quotedblright",
            "quoteleft",
            "quoteright",
            "divide",
            "lozenge",
            "ydieresis",
            "Ydieresis",
            "fraction",
            "currency",
            "guilsinglleft",
            "guilsinglright",
            "fi",
            "fl",
    /* "≥","¥","∏","π","Ω","É","ä","Ç","ã","à","ç","é","è","å","ì","î", */
            "daggerdbl",
            "periodcentered",
            "quotesinglbase",
            "quotedblbase",
            "perthousand",
            "Acircumflex",
            "Ecircumflex",
            "Aacute",
            "Edieresis",
            "Egrave",
            "Iacute",
            "Icircumflex",
            "Idieresis",
            "Igrave",
            "Oacute",
            "Ocircumflex",
    /* nil,"í","ò","ô","ó","ı","√","ƒ","≈","∆","«"," ","À","Õ","Œ","œ" */
            "AppleCorp",
            "Ograve",
            "Uacute",
            "Ucircumflex",
            "Ugrave",
            "dotlessi",
            "circumflex",
            "tilde",
            "macron",
            "breve",
            "dotaccent",
            "ring",
            "cedilla",
            "hungarumlaut",
            "ogonek",
            "caron" /*END*/
        };/*MacintoshEncoding*/

/*END encmacos*/
